<a href="https://colab.research.google.com/github/mickeykubo/analytics_book/blob/master/BasicProgramming2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 関数



プログラムが長くなると，部品を作って何度も再利用したくなります．

Pythonでは，そのようなプログラムの部品のことを*関数*とよび，def で定義します．

基本的な構文は以下の通りです．

```python
def 関数名(引数）:

　　関数本体
  
　　return 返値
```
関数は入力を出力に変換します．

   入力  => 関数   => 出力 
 
入力を「引数（ひきすう）」，出力を「返値（かえりち）」と呼びます．return文はなくても大丈夫です．その場合には返値はありません（Noneという特別なオブジェクトが返されます）．


● 例題７－１

整数nを引数として受け取り，print “#”; を n回繰り返し，長さnの#でできた棒を表示し，その後改行をする関数を作りなさい．

例えば，10 を渡すと
```python
##########
```
が表示され，25を渡すと，
```python
#########################
```
が表示されるような関数を作る，ということです．


In [0]:
def sub(n):
    for i in range(n):
        print('#',end='')

n = int(input('n='))
sub(n)

n=10
##########

● 例題７－２

２つの数字を引数とし，その和を返値として返す関数を記述し，その関数を用いて 3と5の和を計算せよ．また，100と200の和も計算せよ．

複数の引数はカンマで区切って関数に渡します．

関数の値は返値になります．


In [0]:
def computeSum(x,y):
      return x+y 
    
print( computeSum(3,5) )
print( computeSum(100,200) )

8
300


● 例題７－３（再帰）

フィボナッチ数 $F_n$ は

$
F_1 =1  \\
F_2 =1  \\
F_n= F_{n-1} +F_{n-2}
$

と再帰的に定義される数列です．$F_5$ を計算してください．

これは関数 F の中で同じ関数 F を呼び出す再帰的なプログラムで記述します．

In [0]:
def F(n):
    if n==1 or n==2:
        return 1
    else:
        return F(n-1)+F(n-2)
print(F(5))

5


● 問題 7-1

3つの整数を引数として渡すと，その積を返す関数を記述せよ．その関数を用いて，$2*5*7$ と $123*456*234$ を計算せよ．

●問題 7-2

例題7-1の関数を，入力した3つの数を引数として3回呼び出しなさい．例えば8,13,4と入力したら，

```
########

#############

####
```
と，棒グラフのような表示をする，ということです．

●問題 7-3

例題7-1の関数を使って，#でできた三角形を表示するプログラムを作りなさい．
例えば，このようなものを表示するプログラムです．

```
#
##
###
####
#####
######
```

●問題7-4


数aを渡すと，aが正なら1を，負なら -1を，0ならば0を返す関数を作りなさい．

●問題7-5

数aを受け取り，数bをキーボードから入力し，a+bの値を返す関数を作りなさい．

次に，この関数を使って，数を10個入力してその合計を表示するプログラムを作りなさい．

●問題7-6

$n$ の階乗 $n!$ は

$
1! =1 \\
n!= n \times (n-1)! 
$

と再帰的に定義されます．$n!$ を再帰的に計算する関数 Factorial(n) を記述し，$5!$ を計算しなさい．


# 文字列の操作


文字列についてはすでに ' ' もしくは "  "で挟むと生成できることを知っていると思います．

文字列は s ='Hello'は H e l l o が順番に箱に入ってしまわれています．前から順番に 0,1,2, ... と番号付け（添え字とかインデックスといいます）がされています．添え字は range関数と同じように操作できます．

文字 'H'を取り出すには，s[0] とします．

文字 'o' を取り出すには s[4] とします．

文字の範囲はスライス表記 [開始番号: 終了番号 -1] で取り出すことができます．たとえば，

文字列 'He' を取り出すには，s[0:2] とします．


スライス表記の開始番号と終了番号は省略できます．省略すると開始番号は 0 ，終了番号は文字列の長さ（これは len(文字列) で計算できます）になります．

また後ろから番号付けも可能で，最後の文字列の番号は -1，その前の文字列は -2 となります．


$0,2,4$ の添え字の部分から成る文字列 'Hlo' を取り出すには，スライス表記のステップに $2$ を使って s[::2] とします．
開始番号と終了番号を省略したので，最初から最後まで $2$ つ跳びで取り出していることに注意してください．

●例題８－１

文字列 s = 'Hello World' から'World'を取り出してください．

In [0]:
s = 'Hello World'
s[6:]

'World'

文字列は加算演算子 $+$ で結合することができます．たとえば，

'Hello' + 'World' は 'HelloWorld' になります（空白は挿入されません）．

また乗算演算子 $*$ も使うことができます．たとえば， $3*$ 'Hello' とすると 'Hello' +'Hello' +'Hello'  と同じ結果が得られます．

●例題８－２

5回 "I'm sorry!" と出力してみましょう．（文字列の中に'記号を入れたいときには，" "で囲みます．）

In [0]:
print( 5 *"I'm sorry!")

I'm sorry!I'm sorry!I'm sorry!I'm sorry!I'm sorry!


for文を用いた反復はrange関数によって生成された数列だけでなく，文字列に対しても使えます．

たとえば，

```python
for x in 'Hello': 
   print( x )
``` 

と書くと，H, e, l, l, o が順番に変数 x に代入されて，print関数で出力されます．

●例題８－３

文字列 s='Kitty' の各文字の後ろに '!' を入れた文字列 x を出力しなさい．


In [0]:
s = 'Kitty'
x = ''
for i in s:
    x = x + i + '!'
print(x)

K!i!t!t!y!


●問題８－１

文字列を入力し，最初と最後が同じ文字なら 'Same!' と出力するプログラムを作りなさい．

●問題８－２

文字列を入力し，その中に 'a' が含まれているときに 'In!' と出力するプログラムを作りなさい．
（実は  *in* という演算子があるので「 'a' in 文字列」で簡単に 'a'を含むかどうかの判定はできるのですが，ここでは反復を用いて作って下さい．） 


●問題８－３

文字列を引数とすると，各文字の間と最後に空白を入れた文字列を返値として返する関数を作って下さい．
さらに，文字列を入力し，その関数を呼び出して空白を入れた文字を出力するプログラムを書いて下さい．


● 問題８－４

p='Pen', P='Pineapple', a='Apple' を用いて 'PenPineappleApplePen'という文字列を作れ．
また，それを逆から並べた'nePelppAelppaeniPneP'とう文字列を作るプログラムを作成せよ．

また，文字列 p, P, a, p の最初の文字（たとえばpなら'P'）を連結した文字列を生成せよ．

In [0]:
p='Pen'
P='Pineapple'
a='Apple' 

# リスト


Pythonではオブジェクトを保管するための幾つかの便利な機能が（最初から）準備されています．

ここではその代表であるリストの使い方を説明します．

文字列が文字を箱に順番にしまっていたのと同じように，リストは何でも（Pythonではオブジェクトといいます）箱にしまっておくことができます．

リストは[ ]の中に *,*（カンマ）で区切ってものをしまいます．

```python
L = [ 1, 2, 3, 4]               # range(1,5)と同じように数列を保管
L = ['H', 'e', 'l', 'l', 'o']   # 文字列 'Hello' 同じようにう文字を保管
L = [ 'AAA', 235, ['BBB',1.3] ] # 文字列，整数，リストを保管

```

リストに対しても文字列と同じように，足し算，乗算，添え字（インデックス）による抽出や切り出し，for文による反復を行うことができます．

リストは文字列と違って可変(mutable)です（文字列は不変(immutable)です）．つまり中身を変えることができます．


●例題９－１

リスト L=[6, 5, 4, 3] の3番目の数字（Pythonでは0番から始まるので添え字2の数字）を'Hello'に変えて下さい．


In [0]:
L=[6, 5, 4, 3] 
L[2] ='Hello'
print(L)

[6, 5, 'Hello', 3]


●例題９－２

大きさが100の変数のリストaを用意し，0番目に0，1番目に10，2番目に20，…と代入し，最後にそれらを表示する，というプログラムを作りましょう．

aの0番目から9番目までに代入するには，iが0から9まで１ずつ大きくなるfor ループを作り，a[i]に順々に数値を代入すればよいですね．

a[0]には0，a[1]には10，a[2]には20，．．．と代入したいので，a[i]に $i*10$ を代入します．

たとえば，以下のプログラムは，最初に0を入れたリストを10倍することによって，[0,0,0,0,0,0,0,0,0,0]というリストを準備をし，
次のforループで数字の代入を行います．

In [0]:
a=10 * [0]
for i in range(10):
    a[i]=i*10
a

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

リストはいろいろな *メソッド* を適用できます．ここで，メソッドというのはリストに適用される関数のことです．

リストの後に *.* （ピリオド）を打った後に，「メソッド名(引数)」と書くと，関数のように出力が返ってきます．

たとえば，リストの最後に要素を追加するための append メソッドがあります．L.append( 'a' ) と書くと，リスト L の最後に文字列 'a' が追加されます．


上の例題９．２は，最初に空のリストを準備して，1つずつ数字をappendメソッドで追加していく方法でも解くことができます．


In [0]:
a=[]
for i in range(10):
    a.append(i*10)
a

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

例題９．２では，[0,0,...,0] のリストを準備するために $10 *[0]$ と乗算を使いました．

これは以下の *リスト内包表記* と同じですが，リスト内包表記の方が一般的なので推奨される書き方です．

```python
a=[0 for i in range(10)]
```

これは for i in range(10) で iを0から9まで変えた反復を行い，反復ごとに 0 を入れたリストを生成する，という意味です．

0 のかわりに $i*10$ と書けば問題は 1行で解けます．

In [0]:
a=[i*10 for i in range(10)]
a

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


リストの要素を小さい順に並べ替えたいときには，sort()メソッドを使います．
たとえば，
```python
L =[ 6, 8, 3, 1] 
L.sort()
``` 
とすると，Lは [1, 3, 6, 8] と小さい順に並べ変わります．

逆順（大きい順）に並べ替えたいときには，sort()メソッドを使った後に，reverse()メソッドを使います．

●例題９－３

最初の行にimport randomと宣言した上で，x=random.randint(a,b)と書くことで，xにaからbまでのランダムな整数を代入してくれます．

ランダムに生成した1から100までの整数から成る長さ 10 のリストを作り，それを小さい順，大きい順に並べ替えたリストを出力しなさい．


In [0]:
import random
L = [ ]
for i in range(10):
    L.append( random.randint(1,100))
print('元のリスト ', L)
L.sort()
print( '小さい順 ', L)
L.reverse()
print('大きい順 ', L)

元のリスト  [43, 75, 46, 71, 93, 23, 96, 19, 77, 57]
小さい順  [19, 23, 43, 46, 57, 71, 75, 77, 93, 96]
大きい順  [96, 93, 77, 75, 71, 57, 46, 43, 23, 19]


●問題９－１

キーボードから10個の数を入力し，それらを入力された順番と逆の順番で表示するプログラムを作りなさい．

●問題９－２

まず，長さ10に全部 0 が入ったリストを作りなさい．

次に，0から9までの整数 a1,a2を入力し，リストxのa1番目からa2番目までを1大きくする，という作業を繰り返すプログラムを作りなさい．

このとき，毎回リストの0番目から9番目までを表示するようにしなさい．

（ヒント： iをa1からa2までの１ずつ大きくするforループを使い，リストのi番目を1大きくするようにしましょう．）

●問題９－３

リストと整数iを受け取り，リストのi番目の値を１大きくする関数を作りなさい．また，この関数を試すプログラムを作りなさい．


●問題９－４

“Taro”, “Jiro”,”Saburo”,”Shiro”,”Goro” がこの順番で座っている．
この4人を名前を入れたリスト L は

```
L=[“Taro”, “Jiro”,”Saburo”, ”Shiro”, ”Goro”]
```
となる．これを参考にして，自分の座っている列にいる友人の名前のリストを作成せよ．

●問題９－５

上で作成したリストに対して，最初に座っている人と最後に座っている人を表示せよ．

また，名前の昇順のリストを作成せよ．


●問題９－６

100個の1以上10000以下の整数から成るの一様整数乱数のリストを作成し，次にそれらの和と平均を求めよ．

（ヒント：リスト L の和は関数 sum(L) で，要素数は関数 len(L) で求めることができます．）

また，平均に最も近い数を求め，それが何番目の数字（最初の数字を0番目とする）なのかを計算するプログラムを作成せよ．

# タプル

#  

タプルはリストとほとんど同じものですが，リストと違って中身が変更できない不変型(immutable)です．
文字列と同様に（不変型なので）以下で説明する辞書のキーとして使うことができます．

タプルを生成するには () の中に *,* で区切って入力します．

```python
  T =(6,4,7,'Hello')
 ```
 
タプルはリストと同様に添え字（インデックス）や切り出しができますが，中身を変えることができません．

例題１０－１

上のタプルTの4番目の要素（Pythonの添え字は0から始まるので添え字3の要素）を出力せよ．

また，4番目の要素を数字の6に変更してみよ．（エラーが発生するはずです．）


In [0]:
T =(6,4,7,'Hello')
print( T[3])
T[3]=6

Hello


TypeError: 'tuple' object does not support item assignment

例題１０－２

a = 'Hello' と b='World' の2つの変数の中身を1行で取り替えよ．

（aとbから成るタプル (a,b) に (b,a)を代入すると1行で取り替えることができます．

また，() は省略して書くこともできます．

ただし1つの要素から成るタプルの場合には省略できず，*(a,)* とカンマ *,* を入れて書きます． ）


In [0]:
a = 'Hello'
b = 'World'
a,b = b, a
print(a,b)

World Hello


問題１０－１

変数 a,b,c に代入された文字列を変数 x,y,z に代入せよ（ただし1行で）．
```python
a = 'Mickey' 
b = 'Minny'
c = 'Kitty' 
```

変数 a,b,c に代入された文字列を a=>b, b=>c, c=>a になるように交換せよ（ただし1行で）．
```python
a = 'Mickey' 
b = 'Minny'
c = 'Kitty' 
```

# 辞書

#  

リストの他に辞書という便利な機能もあります．辞書は，*キー* を入れると *値*（あたい）が返ってくる写像(マップ）のようなものです．
順番は任意なのでマップ型と呼ばれます．

これは通常の辞書で，"Hello" をひくと「こんにちわ」が書いてあるのと似ています．

辞書は {} をの中に「キー：値」を *,* （カンマ）で区切って入れます．英語を日本語に変換する辞書を作ってみましょう．

```python
D ={ 'Hello' : 'こんにちわ',  'Good Morning': 'おはよう', 'Good Night': 'おやすみ' }

D['Good Morning'] 
```

最初の行で辞書 D を作り，次の行で辞書Dからキー'Good Morning'を引きます．これは対応する値 'おはよう' を返します．

---
3人の女の子の身長を入れた辞書は以下のようになります．

```python
D={ 'Mary': 126, 'Jane': 156, 'Sara': 170} 
```

キーのリストは D.keys() で値のリストは D.values() で得ることができます．

キーになれるのは不変型(immutable)だけです．したがって，リストや辞書などの可変型(mutable)のオブジェクトはキーにはなれません．

キーには数字，文字列，タプルなどを使ってください．

値は任意のオブジェクトを入れることができます．リストや辞書でも大丈夫です．

たとえば，値に身長と体重のリストを入れた辞書は以下のようになります．

```python
D={ 'Mary': [126,30], 'Jane': [156,55], 'Sara': [170,60]} 
```

辞書 D の中にキーがあるかどうかは「キー in D」と*in* 演算子を用いて判定することができます．

たとえば，上で作った身長の辞書Dに対して
```
  'Kitty' in D 
```
は False を返し，
```
  'Mary' in D 
```
は True を返します．


辞書に新しい要素を追加したり，値を変更したいときは，単に「D[キー]=値」と書きます．
たとえば，身長が 10cmの'Kitty'を追加するには
```python
 D['Kitty'] =10 
```
と書き，'Jane'の身長を180に変更したいときには，
```python
 D['Jane'] =180 
```
と書きます．


辞書 D に対してもfor文を使うことができます．構文は for x in D: です．このとき x に代入されるのはキーですが，順番は入力した順ではありません．
（リストや文字列は順序をもつ型（順序型）なので順番が保たれますが，辞書はマップ（写像）型なので順番はばらばらになります．）

●例題１１－１

上で作成した身長の辞書から身長が160cm以上の人の名前を出力せよ．


In [0]:
D={ 'Mary': 126, 'Jane': 156, 'Sara': 170} 
for i in D:
    if D[i] >=160:
        print (i)

Sara


●例題１１－２

上で作成した身長の辞書を，小さい順に並べたときの名前を出力せよ．

まず，身長と名前のタプルを入れたリストをfor文を用いて作ります(この時点では並び順は任意です）．

次にそれを sort()メソッドで小さい順に並べ替えます（並べ替えはタプルの前の要素（この場合には身長）が優先されます）．

並べ替えた後のリストをfor文を用いて反復し，名前を順に出力します．


In [0]:
D={ 'Mary': 126, 'Jane': 156, 'Sara': 170} 
L = []   #空のリストを準備しておく
for i in D:
    L.append( (D[i], i) ) #（身長，名前）のタプルをリストに追加
print('並べる前のリスト ' , L)
L.sort()
print('身長順のリスト ' , L)
for (height,name) in L:
    print( name )

並べる前のリスト  [(126, 'Mary'), (156, 'Jane'), (170, 'Sara')]
身長順のリスト  [(126, 'Mary'), (156, 'Jane'), (170, 'Sara')]
Mary
Jane
Sara


●例題１１－3

辞書に対する**for**文はキーを返しますが，**辞書.items()** とすると，キーと値のタプルを返します．

これを用いて，辞書D={ 'Mary': 126, 'Jane': 156, 'Sara': 170} のキーと値を入れ替えた辞書（身長を入れると名前を返す辞書）を作成しなさい．



In [0]:
D={ 'Mary': 126, 'Jane': 156, 'Sara': 170} 
Reverse = {}
for key, value in D.items():
  Reverse[value] = key 
print(Reverse)

{126: 'Mary', 156: 'Jane', 170: 'Sara'}


●問題１１－１

名前をキー，体重を値とした辞書 D を作成せよ．ただし，友人は3人以上記入し，
名前には友人の名前を文字列として，体重には友人の理想体重を整数値として入力せよ．

●問題１１－２

起動すると，友人の名前の入力を求め，上で作成した辞書Dから体重を調べて画面上に表示するプログラムを作成せよ．

●問題１１－３

上のプログラムを，何度も友人の名前の入力を求めるように変更せよ．ただし，辞書にない名前を入力すると終了するものとする．

●問題１１－４

空の辞書Dを準備し，その後で名前と体重の入力を何度もユーザーに要求して，
名前をキー，体重を値としてDに保管していくプログラムを作成せよ．
ただし，ユーザー名に空白 ”” を入力すると，画面に作成した辞書Dを表示してから，終了するものとする．


●問題１１－５

友人の名前と体重を保管した辞書Dを準備し，その後で，友人の名前と体重の入力を求め，名前が一致する友人がいたならば，
体重を新しい値に変更し，いなければ辞書に追加するプログラムを作成せよ．
ただし，ユーザー名に空白 ”” を入力すると，画面に作成した辞書Dを表示してから，終了するものとする．

●問題１１－６

問題１１－１で作成した友人の名前と体重を保管した辞書Dの名前を体重を名前のアルファベット順に画面に出力するプログラムを作成せよ．

●問題１１－７

好きな都道府県を5つ選択した後，都道府県名をキーとし，その名産品（1つ以上入力する）のリストを値とした辞書Dを作成せよ．

また，作成した辞書に対して，名産品の多い順に並べるプログラムを作成せよ．

(ヒント：リストLの長さ(要素数）は関数len(L)で計算できます．）

# クラス

#  

Pythonでは，数やリストや辞書などはすべてオブジェクトと呼ばれます．これらのオブジェクトは元から準備されたものなので組み込みオブジェクトと呼ばれます．

Pythonでは，自分で新しいオブジェクトを作ることができます．それがクラス(class)です．

構文は関数と似ています．関数を定義するキーワード def の代わりに class と書きます．

```python
class クラス名():
    クラス本体
```

クラスとは，オブジェクトの属性やオブジェクトに対する操作（これをメソッドと呼びます）をまとめたものです．

たとえば，ピカチュウというクラスは，「ほっぺた」や「しっぽ」などの属性と，「しっぽを振る」とか「リンゴを食べる」といったメソッドをもちます．

例として「点」を表すクラス Point を作ってみましょう．

```python
class Point():
    pass

p1=Point()
```

pass は何もしないことを表します（何も入れないとエラーします）．クラス名は Point で，```p1=Point()```でp1というクラスの実体（インスタンスと言います）を生成しています．

p1 という点を表すインスタンスには，x座標とy座標という**属性** (attribute)をもたせることができます．

属性はインスタンスの後ろに **.** を書いた後に記述します．

```python
p1.x = 100
p1.y = 200
```
これで点p1にx,y座標の属性100,200をもたせることに成功しました．

次に，点を移動させるとか，座標をまとめて出力するといった**メソッド** (method) を記述しましょう．

メソッドは，クラス定義の**中**で関数と同様に def と書くことで定義できます．

ただし，メソッドの最初の引数には必ず自分自身を表す**self**を入れます．クラス内でx属性にアクセスするときには，**self.x**と記述します．

●例題１２－１

点を表すクラス Point を作成し，x座標とy座標を表す属性に100,200を代入してください．

次に，座標の出力を行うメソッドprintMeを用いて座標の出力を行ってください．

また，座標の移動を行うメソッドmoveを定義し，座標を右に10，上に20移動させてから座標の出力を行ってください．


In [0]:
class Point():
    def printMe(self):
        print( "<", self.x, ",", self.y, ">" )
    def move(self,right,up):
        self.x+=right
        self.y+=up
p1=Point()
p1.x = 100
p1.y = 200
p1.printMe()
p1.move(10,20)
p1.printMe()

< 100 , 200 >
< 110 , 220 >


クラスには```__``` (アンダースコア2つ）で挟んだ特殊メソッドを定義することができます．

たとえば文字列を返す**__str__**を定義すると，クラスのインスタンスをprintしたときに，その文字列が表示されるようになります．

クラスの初期化を行うメソッド**__init__**を定義すると，インスタンスを最初に生成したときに「自動的に」呼ばれ，インスタンスの初期化を行うことができます．

たとえば，点のインスタンスを生成するときに「必ず」x,y座標を与えて，x,y属性に代入するには，

```python
    def __init__(self, x, y):
        self.x=x
        self.y=y
```
と記述します（最初の引数に**self**を入れるのを忘れないようにしてください）．

ただし，点クラスのインスタンスを生成するときには，**self**は書かずに，以下のように記述します．

```python
p1=Point(100,200)
```

●例題１２－２

初期化をするためのメソッド```__init__```を用いて点を表すクラス Point を作成し，x座標とy座標を表す属性に100,200を代入してください．

また，文字列を返す```__str__```を用いて座標の出力を行ってください．

さらに，他の点インスタンスの座標を加える特殊メソッド```__add__```（これは + 演算子を適用したときに呼ばれます）を
使って座標 (10，20) をもつ点インスタンスとの足し算をしなさい．
        

In [0]:
class Point:
    def __init__(self, x, y):
        self.x=x
        self.y=y
        
    def __str__(self):
        return "<"+ str(self.x) + ", " + str(self.y) +">"
    
    def __add__(self, other):
        return Point( self.x+other.x, self.y+other.y )
    
p1=Point(100,200)
print( p1)
p2=Point(10,20)
print( p1+p2 )

<100, 200>
<110, 220>


●問題１２－１

身長と体重の2つの属性をもつHumanクラスを作成してください．

その後に，「体重/身長の2乗」で定義されるボディマス指数を計算するメソッド bmi を追加してください．
（ただし，体重はキログラム，身長はメートルで入れます．）

次に，以下の表に基づいて，痩せ型から肥満(4度）までのいずれに属するかを文字列として返すメソッド am_i_fat を追加してください． 

                     BMI値
    痩せ型     	18.5未満
    普通体重	   18.5以上、25未満
    肥満（1度）	25以上、30未満
    肥満（2度）	30以上、35未満
    肥満（3度）	35以上、40未満
    肥満（4度）	40以上
    
自分の身長と体重（公表するのが嫌な場合には，友人の身長と体重）を属性としたHumanのインスタンス me を作成して，am_i_fatを呼んでみましょう．



●問題１２－２

例題で作った点を表すクラスを参考にして，ベクトルを表すクラスを定義し，2つのベクトルの内積を乗算 $*$ で行うようなメソッド
```__mult__```を書いてみましょう．

#  内包表記


リストのところで内包表記 (comprehension) について簡単に触れました．
ここでは，内包表記を一般的に説明します．

* リスト内包
* 辞書内包
* ジェネレータ内包




##  リスト内包

ｰ 1から9までの奇数のリストを生成するには，リスト[ ] の中にfor文を入れて，以下のように記述します．

```python
a = [0 for i in range(1,10,2)]
print(a) 
>>> 
[1, 3, 5, 7, 9]
```

if文をfor文の後ろに入れて条件付きで反復することもできます．
```python
a = [i for i in range(10) if i%2==1]
print(a)
>>>
[1, 3, 5, 7, 9]
```


●問題 

20から100の整数で3で割り切れるものだけから成るリストを，リスト内包で生成せよ．


●問題

"aa", "bb", "cc", "dd", "ee" から成るリストを，文字列 s= "abcde" からリスト内包を用いて生成せよ．

In [0]:
 s= "abcde" 
 #ここにコードを記述せよ．

## 集合内包

リストの[ ] のかわりに{ }を用いることによって，集合を生成する集合内包ができます．

●問題

上でリストを生成したかわりに集合を生成せよ．


## 辞書内包


{  } 内でfor文を書いて，キー:値を入れることによって辞書を生成できます．これを辞書内包とよびます．

1から10の整数をキーとし，その2乗を値とした辞書は，以下のように辞書内包を用いて生成できます

```python
{i:i**2  for i in range(1,11)}
>>>
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
```

●問題
1から10までの整数をキーとし，"#"をキー個並べた文字列を値とした辞書を，辞書内包を用いて生成せよ．

●問題

辞書  D= {1:"one", 2:"two",3:"three",4:"four" } から，英字の数字文字列("one"とか"two"とか)をキーとし，数字(1とか2とか)を値とした辞書を辞書内包を用いて生成せよ．

In [0]:
D= {1:"one", 2:"two",3:"three",4:"four" } 

## ジェネレータ内包

リストの[]，集合や辞書の{}のかわりに( ) を用いると，要素を順に「生成する」オブジェクトが得られる．これをジェネレータ内包と呼ぶ．
()の前にsum関数などを書くと，内包で要素をすべて生成せずに，順に生成しながら合計がとれる．

たとえば，1から10までの数字の和は以下のようにジェネレータ内包で記述できます．
```python

sum( i for i in range(1,11))
>>>
55
```

●問題

1から100までの奇数の和を計算せよ．



●問題

$x$ を -100から100まで1づつ増やしたとき，$x^2 + 2x -5 $ の最小値の値を，ジェネレータ内包を用いて計算せよ． 


# zip の使い方

2つ以上のリストの要素を**for**文で順に1つずつ取り出したいときには，**zip**関数が便利です．

**zip** はzipper（ジッパー）のように，2つのものを1つにまとめてくれます．

たとえば，体重のリストweightと名前のリストnameがあったとき，順に取り出して出力するには，以下のようにします．

```python 
weight = [50,60,70]
name =[ "Taro", "Hanako", "Jimmy"]
for w,n in zip(weight,name):
     print(w,n)
 
 >>>
50 Taro
60 Hanako
70 Jimmy
    ```

●問題

身長と名前を入れた2つのリストがあったとき，これらを順に反復して，名前をキーとし身長を値とした辞書を生成せよ．できれば，辞書内包を用いて1行で記述せよ．

In [0]:
height = [150,160,170]
name =[ "Taro", "Hanako", "Jimmy"]
#以下に1行で書く：


●問題

身長，体重，名前の3つのリストがあったとき，**zip**関数を用いて出力せよ．

In [0]:
height = [150,160,170]
weight = [50,60,70]
name =[ "Taro", "Hanako", "Jimmy"]



# エラー


プログラムにはエラーがつきものです．エラーが発生したときに，どのような処理をするかは**例外処理**とよばれ，これをあらかじめ組み込んでおくことによって，頑強なプログラムを作成することができます．


構文は**if**文と類似していて，以下のように書きます．

```python
try:
    エラーが試される文
except エラー名:
    エラー発生時の例外処理
else: 
    エラーが発生しないときの処理    

```

●例題

10/xを計算しyに代入してから出力するプログラムを xが0のときに発生するエラー(ZeroDivisionError)の処理を入れて記述せよ．

In [3]:
x = 0
#x = 1
try:
  y = 10/x
except ZeroDivisionError:
  print("0では割れないよ!")
else:
  print(y)

0では割れないよ!


●問題 

どのようなエラー名なのかは，実際にエラーを発生させてみると分かります．

```python

x = [1,2,3]
print(x[3])
```
と入力してみましょう．
**IndexError** と出力されるはずです．

このエラー名を使って，iを0から5まで１づつ増やしながら反復させてx[i]を出力させたとき，
対応するインデックスがない場合には，「そんな添え字はないよ」と出力するプログラムを作れ．



In [0]:
x = [1,2,3]
